# Generated by Django 5.2.6 on 2026-01-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_learningsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('learner_3', 'Learner - 3 Skills'), ('learner_5', 'Learner - 5 Skills'), ('learner_10', 'Learner - 10 Skills'), ('teacher_3', 'Teacher - 3 Skills'), ('teacher_5', 'Teacher - 5 Skills'), ('teacher_10', 'Teacher - 10 Skills')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
