# Generated by Django 5.2.6 on 2026-01-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_badge'),
    ]

    operations = [
    ]
