# Generated by Django 5.2.6 on 2026-04-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_useractivitysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill_name', 'id'],
                'indexes': [models.Index(fields=['skill_name'], name='api_skillqu_skill_n_0e163f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('score', models.IntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_date', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'skill_name'], name='api_teacher_teacher_685f1a_idx'), models.Index(fields=['is_verified'], name='api_teacher_is_veri_c8900c_idx')],
                'unique_together': {('teacher', 'skill_name')},
            },
        ),
    ]
